const SURL='https://nzwbgzhlffnzbadggmwz.supabase.co/rest/v1/';
const SKEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56d2JnemhsZmZuemJhZGdnbXd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0OTY5OTYsImV4cCI6MjA5MTA3Mjk5Nn0.F5azP3KRBqIkfMCzwFrb-dlkv_SyUmjBhB7VrT3xK1Q';

const adjectives=['Gentle','Quiet','Brave','Kind','Humble','Sincere','Hopeful','Patient','Grateful','Resilient','Thoughtful','Warm','Calm','Faithful','Tender','Strong','Honest','Caring','Peaceful','Wise','Modest','Bright','Loyal','Noble','Steadfast','Devoted','Joyful','Blessed','Radiant','True'];
const nouns=['Heart','Soul','Moon','Star','River','Light','Garden','Breeze','Mountain','Ocean','Dawn','Sage','Sparrow','Falcon','Meadow','Willow','Cedar','Pearl','Horizon','Spring','Haven','Rain','Cloud','Echo','Shore','Bloom','Petal','Stone','Wave','Flame'];

function randName(){return adjectives[Math.floor(Math.random()*adjectives.length)]+' '+nouns[Math.floor(Math.random()*nouns.length)];}
function randLikes(){return Math.floor(Math.random()*45);}
function randDate(){
  var d=new Date();
  d.setDate(d.getDate()-Math.floor(Math.random()*60));
  d.setHours(Math.floor(Math.random()*24),Math.floor(Math.random()*60));
  return d.toISOString();
}

const marriage=[
"I'm 26 and my parents keep rejecting every person I bring home because they're not from our culture. I found someone who is kind, practicing, and treats me with so much respect. But my parents won't even meet them. How do I honor my parents while also not losing someone who might be my naseeb?",
"My husband told me he doesn't find me attractive anymore. We've been married 3 years. I don't even know how to look at myself in the mirror now. Has anyone come back from something like this?",
"I caught my wife texting another man. She says it was nothing but I read the messages. My heart is shattered. I have two kids. I don't know if I should stay or leave. I can't eat, can't sleep. Please make dua for me.",
"I've been doing istikhara for 6 months about this person and I still don't have clarity. Everyone says you'll just 'know' but I don't. Am I overthinking this or is the lack of clarity itself the answer?",
"My fiancé just called off our engagement 2 weeks before the wedding. Everything was booked. My family is humiliated. I feel like damaged goods now. Will anyone ever want me after this?",
"I'm a 30-year-old woman and I've never been proposed to. Not once. I pray tahajjud every night asking Allah to send me someone. Sometimes I wonder if marriage just isn't written for me. The loneliness is unbearable.",
"My in-laws are destroying my marriage. They live with us and my mother-in-law criticizes everything I do. My husband always takes her side. I feel like a stranger in my own home. Is this what marriage is supposed to be?",
"Married for 7 years and we haven't been intimate in over a year. We're more like roommates than spouses. Neither of us talks about it. I'm too embarrassed to bring it up with an imam. How do couples fix this?",
"I'm in love with someone who isn't Muslim. I know the ruling. Please don't lecture me. I just need someone to understand how painful it is to walk away from someone you love because of your faith. I chose Allah but my heart is broken.",
"My parents want me to marry my cousin back home. I've met him once when I was 12. I have nothing against him but I want to choose my own spouse. Every time I bring it up my mom cries and says I'm being ungrateful.",
"I got divorced at 24. I'm now 27 and when I tell potential matches I'm divorced, they immediately lose interest. Being a young divorcée in the Muslim community feels like wearing a scarlet letter.",
"My husband doesn't pray. Not even Jummah. Before we got married he seemed practicing. I feel deceived but I also love him. Can I raise righteous children with a husband who doesn't pray?",
"I'm seriously considering a second wife and I don't know how to tell my first wife. I love her but I feel something is missing. I know my rights in Islam but I also know this will destroy her. What do I do?",
"She said yes to the proposal but I can tell her parents pressured her. She barely looks at me during our supervised meetings. I want a wife who genuinely wants me, not one who was forced. Should I back out?",
"I have a past. Before I became practicing, I made mistakes. Now someone wants to marry me and I don't know if I should tell them about my past or keep it between me and Allah. The guilt is eating me alive.",
"My mahr was $50,000 and my husband reminds me of it every argument. 'I paid fifty thousand for you.' It makes me feel like property. Is this normal?",
"We've been trying to have children for 4 years. Every pregnancy announcement on social media feels like a knife. People keep asking 'when are you having kids?' as if we're not trying. As if we're not devastated.",
"I found out my wife has $40,000 in debt she hid from me before marriage. I feel betrayed. We're supposed to be a team but she started our marriage with a massive lie. How do I trust her again?",
"I want to marry someone from a different sect. My family is Sunni, she's Shia. We agree on all the fundamentals. But both families are treating this like we're committing a crime. Love shouldn't be this hard.",
"My husband watches things he shouldn't online. I found it on his phone. He cried and promised to stop but I caught him again. I feel like I'm not enough. My self-worth is on the floor.",
"I'm ready for marriage but I literally cannot afford it. The walima expectations, the mahr, getting an apartment — I need at least $15,000 just to get started. How is a 25-year-old supposed to do this?",
"My wife wants to work and I want her to stay home with the kids. She says I'm being controlling but I genuinely believe it's better for the children. We argue about this weekly. There's no compromise in sight.",
"Everyone keeps telling me to 'lower my standards' but I don't think wanting someone who prays five times a day, has a stable job, and is kind is too much to ask. Why do people treat women who have standards as the problem?",
"My mom did black magic on my marriage. I'm not making this up. I found the taweez under our mattress. My own mother. Since then everything has fallen apart. I don't know who to trust anymore.",
"I met someone on a Muslim marriage app and we talked for 3 months. Deep conversations every night. Then he ghosted me completely. No explanation. I'm devastated and I don't even know his real name.",
"My wife gained weight after our baby and honestly I'm struggling with attraction. I feel terrible even thinking this way. I love her soul but I don't know how to bring this up without destroying her.",
"I'm a revert and finding a Muslim spouse is nearly impossible. Muslim families don't want their children marrying a convert. They smile at the masjid but won't let me into their homes. It's heartbreaking.",
"We've been married 12 years and I just discovered my husband has a secret second wife. He married her 2 years ago. I had no idea. My entire reality has collapsed. I don't even know who I'm living with.",
"I have severe anxiety and it's ruining my marriage. I overthink everything my husband says, I need constant reassurance, and I have panic attacks when he doesn't text back quickly. He's patient but I can see he's getting tired.",
"I made istikhara and had the most beautiful dream. Green fields, peace, I felt certain. But then the proposal fell through. Now I question everything — did I misread the signs? Did Allah say no and I wasn't listening?",
"My family spent $80,000 on my sister's wedding. Now it's my turn and they say they can't afford more than $5,000 for mine. The double standard between sons and daughters in our community is real.",
"I love my wife but I don't love her cooking and she makes dinner every night. She puts her heart into it. I've been secretly eating at work before coming home. I feel terrible but I don't want to hurt her feelings.",
"We agreed before marriage that I could continue my education. Now that we're married, my husband says a wife's place is at home and I should drop out. I'm one semester away from my degree. I feel trapped.",
"I'm 34 and male. Everyone says men can wait but the truth is, the loneliness is killing me too. I come home to an empty apartment every night. I make dua but sometimes I wonder if Allah has forgotten me.",
"My ex-wife is turning my kids against me. They don't want to come for my weekends anymore. She tells them things about me that aren't true. I cry after every phone call with them. Divorce is the worst thing I've experienced.",
"I'm attracted to someone at work and it terrifies me. I'm happily married but this feeling won't go away. I've started avoiding them but we're on the same team. I haven't told anyone. The guilt alone is crushing.",
"My parents had an arranged marriage and they're miserable. They argue every day. Now they want me to do the same thing. How can I trust their judgment when their own marriage is falling apart?",
"I got married last month and I feel nothing. No spark, no excitement. Everyone says feelings come later but what if they don't? Did I make the biggest mistake of my life?",
"My husband told me he's not ready for kids. We're both 32. He says 'maybe next year' every year. I'm watching my fertile years pass by and he doesn't seem to care. I feel like my body is on a timer he's ignoring.",
"I spent $2,000 on a dating app and went on 15 meetings with potentials. Not a single one worked out. I'm starting to think there's something fundamentally wrong with me that everyone can see except me.",
"My wife is more religious than me and it makes me feel inadequate. She prays tahajjud, reads Quran daily, wears niqab. I struggle to pray fajr on time. She never says anything but I can feel her disappointment.",
"I told my parents I want to marry a Black Muslim woman. They said they'd disown me. In 2026. The racism in our community disguised as 'culture' makes me sick. I'm marrying her anyway. Make dua for us.",
"My husband travels for work 3 weeks out of every month. I'm essentially a single mother. When he's home, he's exhausted and just wants to rest. I love him but I'm drowning and he can't see it.",
"I found out the man I've been talking to for marriage is already married. He never mentioned it. When I confronted him, he said he was 'going to tell me eventually.' How are there men like this in our ummah?",
"We can't agree on how to raise our kids islamically. I want Islamic school, she wants public school with weekend madrasa. I want hijab at puberty, she says it should be their choice. These aren't small disagreements.",
"I'm a widow at 29. My husband passed away in a car accident. People have started suggesting I remarry 'for the sake of the children.' It's been 4 months. I haven't even finished grieving. Please just let me breathe.",
"My fiancée wants a $30,000 mahr. I come from a humble family. When I suggested something lower, her family acted offended. I thought mahr was supposed to be reasonable, not a transaction. Am I wrong?",
"I've been making dua for a righteous spouse for 8 years. Eight years. I've done everything — apps, events, asking family, walis, istikhara. Nothing. I'm starting to resent the married people who tell me to 'be patient.'",
"My mother-in-law told my wife she should have married someone better. Right in front of me. At dinner. My wife didn't defend me. That silence told me everything I needed to know about where I stand.",
"I married for love against my family's wishes. They were right — he changed completely after the wedding. The charming man I fell for became controlling and cold. Now I'm too ashamed to go back to my family.",
"We do everything halal — supervised meetings, involved families, istikhara. But when we finally got married, we realized we're completely incompatible. How does this happen when you do everything right?",
"I want nikkah only, no big wedding. My family is acting like I'm committing a crime. 'What will people say?' is their favorite sentence. I'm trying to follow the Sunnah and they're making it impossible.",
"My husband doesn't want me to wear hijab. He says it draws unwanted attention and he prefers how I look without it. Choosing between my husband's wishes and Allah's command is tearing me apart.",
"I got rejected for being 'too dark.' The aunty literally said 'she's lovely but a bit dark for our family.' My skin color. In 2026. In the ummah of Muhammad (SAW) who said no Arab is superior to a non-Arab.",
"My wife and I haven't spoken to each other in two weeks. We live in the same house, eat at the same table, sleep in the same bed. Complete silence. Neither of us knows how to break it. The cold is worse than any fight.",
"I'm considering marriage but I have student loans totaling $120,000. I feel like no one will want me with this financial burden. Do I wait until it's paid off? That could take 10 years.",
"My parents approve of him. He prays. He has a good job. He's kind. But I feel absolutely nothing when I look at him. Everyone says attraction grows. But what if it doesn't? Am I being foolish for wanting butterflies?",
"I secretly got married without my family's knowledge because they would never approve. It's been 6 months. The lying is eating me alive but telling the truth might cost me my family forever. I'm stuck.",
"My wife asked for a divorce and I don't know why. She says she's just 'not happy' but can't explain what's wrong. I've been the best husband I know how to be. I'm blindsided and completely lost.",
"I used to think a perfect Muslim marriage existed. After 10 years, I've learned it doesn't. What exists is two imperfect people choosing each other every single day. And some days, that choice is really, really hard.",
"My parents want $25,000 for my sister's mahr because 'that's what our family deserves.' She's embarrassed and doesn't want to scare away a good man over money. I'm on her side but my parents won't listen.",
"I'm 28 and my younger sister got married before me. The way relatives look at me with pity at family gatherings makes me want to disappear. I'm happy for her but the comparisons are constant and cruel.",
"Alhamdulillah for everything but marriage is genuinely the hardest thing I've ever done. No one tells you about the loneliness you can feel even when you're not alone. Pray for all of us who are struggling quietly.",
"I was in a haram relationship for 3 years before becoming practicing. That person wants to do things the right way now and approach my parents. But they know about our past. How do we make this halal without exposing our sins?",
"My husband told me he married me because his mom chose me, not because he wanted to. Five years and two kids later. I've been living a lie. Every 'I love you' was empty. I don't know how to process this.",
"My wife is an amazing mother but I feel like she's forgotten she's also a wife. Everything revolves around the kids. I miss her. I miss us. I feel selfish for even feeling this way.",
"I have a physical disability and every proposal gets rejected once they find out. My character, my deen, my education — none of it matters once they see the wheelchair. The ummah preaches equality but doesn't practice it.",
"I found the perfect person — practicing, kind, compatible in every way. But they live in another country and neither of us can relocate. Sometimes I think Allah shows us what we can't have to test our sabr.",
"My father-in-law keeps lending my husband money and then holding it over our heads. He controls our finances through these 'loans.' My husband won't stand up to him and I'm suffocating.",
"I've been engaged for 2 years because he keeps pushing the wedding date. First it was finances, then his career, now his family 'isn't ready.' I think he's just not sure about me but doesn't have the courage to say it.",
"My wife confided that she was abused as a child. I don't know how to help her. She has nightmares and sometimes flinches when I touch her. I love her so much. How do I support her without making it worse?",
"I'm a single mother of 3 and I've been told I'm 'baggage' by multiple potential matches. I'm not baggage. I'm a woman who survived, who provides, who loves fiercely. My children are not a burden. They're a blessing.",
"Everyone in my family married young — 18, 19, 20. I'm 23 and unmarried and they treat me like there's something wrong with me. There's nothing wrong with me. I'm just waiting for the right person. Why is that a problem?",
"My husband just told me he wants us to move to another country for his career. I'll have to leave my family, my friends, my job. He didn't ask — he told. Is this what qawwam means? Because it feels like dictatorship.",
"I pray salatul hajah every night for marriage. Last night I cried so hard in sujood that I couldn't breathe. I know Allah hears me. I know His timing is perfect. But the waiting is so heavy sometimes.",
"My wife and I argue about money constantly. She spends, I save. She says I'm cheap, I say she's irresponsible. We've tried budgets but they last a week. Money is destroying something that used to be beautiful.",
"I converted for marriage. I know you're not supposed to but I was honest about it. I thought love would be enough. Three years later, I genuinely love Islam but my husband treats my faith as less valid because of how it started.",
"My parents divorced when I was 10 and it broke something in me. Now I'm engaged and I'm terrified of repeating their mistakes. I overthink every disagreement, convinced it's the beginning of the end. How do I heal from their marriage?",
"I accidentally saw my husband's search history and he's been researching marriage to a second wife. He hasn't mentioned anything to me. Do I confront him or wait? My stomach has been in knots for days.",
"We both want kids but we just found out I'm infertile. The doctor confirmed it. My wife says she's okay with it but I can see the sadness she's trying to hide. I feel like I've failed her in the most fundamental way.",
"I married someone my parents chose. 15 years later, I can honestly say they were right. We struggled in the beginning — we were strangers. But the love we built is deeper than anything I could have found on my own. Sabr works.",
"My engagement was called off because his family found out my brother was in prison. I'm not my brother. I've never done anything wrong. But in our community, one person's mistake stains the entire family.",
"I want a simple nikah — just close family, good food, and sincere dua. But 'simple' in our community apparently means 'you don't love your daughter enough.' The pressure to go into debt for a wedding is insane.",
"My wife earns more than me and it bothers me. I know it shouldn't. I know it's my ego. But when her family makes comments, it cuts deep. I provide for my family but apparently not enough in their eyes.",
"I'm in a polygamous marriage and it's not what social media makes it look like. The jealousy, the scheduling, the feeling of never being enough — it's a constant test. I consented but I underestimated the pain.",
"My husband hasn't said 'I love you' in 3 years. When I tell him, he says 'you know how I feel.' But I need to hear it. I need words. Is wanting verbal affirmation too much to ask from your own spouse?",
"I found someone through the masjid who checks every box. But she's 8 years older than me. My family says the age gap is inappropriate. In Islam, Khadijah (RA) was 15 years older than the Prophet (SAW). Why the double standard?",
"My ex-husband told everyone at the masjid that I was the reason for our divorce. He painted me as a bad wife. Now the community treats me differently. Nobody asked for my side of the story. The court of public opinion in the ummah is ruthless.",
"I've been through 3 failed engagements. Three. Each time I pick myself up, make dua, and try again. People say 'what's wrong with you?' but the truth is, I'd rather be single than settle for someone who doesn't value me.",
"My husband is a wonderful person but a terrible communicator. I have to guess what he's feeling. When I ask what's wrong, he says 'nothing.' We need help but he thinks therapy is for 'crazy people.' How do I reach him?",
"I'm about to propose but I'm terrified of rejection. Her family is wealthier and more educated than mine. I'm a good man with a good heart but I don't have a prestigious last name or a six-figure salary. Will that be enough?",
"My wife's best friend is a man. He's been her friend since college. She says I'm being insecure but I'm uncomfortable with it. Am I wrong for setting this boundary or am I being controlling?",
"Alhamdulillah, after 7 years of making dua, I finally got married last week. To anyone still waiting — don't give up. Allah's timing broke me but it also built me into someone ready for this blessing. Your time is coming.",
"My mother-in-law moved in 'temporarily' 6 months ago. She rearranged my kitchen, changed the kids' routines, and constantly compares me to her other daughters-in-law. My home doesn't feel like mine anymore.",
"I married young — we were both 19. Everyone said we were too young. Seven years later, we've grown up together and our marriage is my greatest blessing. Young marriage isn't for everyone but it was right for us.",
"My fiancé wants me to sign a prenup. I feel like he's already planning for failure before we've even begun. He says it's practical, I say it's unromantic. Can a marriage built on contracts ever feel sacred?",
"I dream about someone other than my spouse. It happened once and I felt guilty. Then it happened again. And again. I would never act on it but the guilt is consuming me. Is this normal?",
];

const mentalHealth=[
"I've been smiling at the masjid for years while falling apart inside. Nobody knows. I lead prayers, I teach the kids, I organize events. But when I go home, I sit in the dark and feel nothing. The mask is getting heavier.",
"I was diagnosed with depression and my mom said 'just make more dua.' I pray five times a day. I read Quran every morning. I still can't get out of bed some days. Why does the ummah treat mental illness like a faith deficiency?",
"I had a panic attack during Jummah. Right there in the masjid, surrounded by hundreds of people. My heart was racing, I couldn't breathe, I thought I was dying. I left and haven't been back in 3 weeks. I'm too embarrassed.",
"I'm a therapist and I'm struggling with my own mental health. The irony isn't lost on me. I spend all day helping others while my own anxiety is through the roof. Who does the healer go to when they need healing?",
"I've been having thoughts about ending my life. I'm not going to do it — I know it's haram. But the thoughts come anyway, uninvited, persistent. I'm exhausted from fighting my own mind. If you're reading this, please just make dua for me.",
"My OCD makes me repeat wudu 7-8 times because I'm never sure it's 'right.' Prayer takes me 45 minutes because of waswasa. What's supposed to bring me peace has become my biggest source of anxiety.",
"I was sexually abused by a Quran teacher when I was 9. I've never told anyone. I'm 24 now and I still can't open the Quran without feeling sick. I want my relationship with Allah back but the trauma stands between us.",
"I cry every night but in the morning I put on a smile and go to work. I've been doing this for 2 years. I'm so tired of performing okay-ness. Some days just existing takes everything I have.",
"My husband told me my anxiety is 'not that serious' and I should 'just relax.' If I could 'just relax,' don't you think I would? The loneliest feeling is being dismissed by the person who's supposed to understand you most.",
"I developed an eating disorder during Ramadan. The fasting triggered something in me and now I can't eat normally even outside of Ramadan. Everyone praised my weight loss. Nobody noticed I was destroying myself.",
"I was addicted to substances for 3 years. Alhamdulillah I'm clean now — 14 months. But the shame follows me everywhere. In the Muslim community, there's no room for people who've struggled with addiction. We just get judgment.",
"I have bipolar disorder and during my manic episodes I spent $15,000 we didn't have. My family thinks I'm irresponsible. They don't understand that my brain literally hijacks my decision-making. I'm not reckless — I'm sick.",
"My social anxiety is so bad that I haven't been to a gathering in over a year. Eid comes and I make excuses. Weddings, I send a gift. The community thinks I'm antisocial but the truth is, being around people physically hurts.",
"I'm a hafiz and I can't feel the Quran anymore. I recite the words perfectly but they feel empty. I used to cry during recitation. Now I feel nothing. Spiritual numbness is its own kind of depression and nobody talks about it.",
"I started therapy 6 months ago and it's changing my life. For anyone hesitant — it's not against Islam. Taking care of your mental health IS taking care of the amanah Allah gave you. Your mind is worth investing in.",
"My intrusive thoughts tell me terrible things about Allah. I know they're from Shaytan. I know I don't believe them. But they still come and the guilt makes me feel like the worst Muslim alive. Does anyone else experience this?",
"I had postpartum depression after my second child and my husband told the whole family I was 'being dramatic.' His mother offered to take the baby because apparently I 'couldn't handle it.' The lack of understanding almost killed me — literally.",
"I'm a man and I've been depressed for years but I can't talk about it because in our culture, men don't struggle. We provide, we stay strong, we don't cry. I'm drowning behind a wall of toxic expectations.",
"My daughter has ADHD and our community treats her like she's badly raised. 'She just needs discipline.' No, she needs understanding. Her brain works differently. Stop blaming parents for neurological conditions.",
"I've been clean from self-harm for 200 days. It's the longest I've gone. Some days are harder than others but I'm still here. If anyone is struggling with this — recovery isn't linear but it IS possible. You're not alone.",
"I lost my faith during my depression. For two years, I didn't pray, didn't fast, didn't care. Now that I'm healing, the guilt of those lost years is almost as heavy as the depression itself. Does Allah forgive abandonment?",
"My anxiety medication conflicts with fasting during Ramadan. Every year I have to choose between my mental health and participating in the most sacred month. The guilt of not fasting is its own form of suffering.",
"I'm a psychiatrist and I want the ummah to know: medication for mental illness is no different than medication for diabetes. Your brain is an organ. When it's sick, it needs treatment. Stop telling people to 'just pray more.'",
"I dissociate during stressful conversations. I literally leave my body. It started after trauma in my childhood. People think I'm spacing out or not listening. I'm actually somewhere far away, trying to feel safe.",
"My mother has undiagnosed mental illness and she refuses to get help because 'Muslims don't need therapists, we have Allah.' I love her but watching her suffer while refusing help is breaking my heart.",
"I was bullied severely at Islamic school and it gave me PTSD that I still deal with at 26. The very place that was supposed to nurture my faith became the source of my deepest trauma. The irony is devastating.",
"I use humor to cope and everyone thinks I'm the funny friend, the one who's always happy. Nobody asks if I'm okay because why would they? I'm always laughing. But laughter and pain live in the same house sometimes.",
"My therapist is non-Muslim and she understands me better than anyone at the masjid ever has. She doesn't judge me, doesn't minimize my feelings, doesn't tell me to pray harder. She just listens. Sometimes that's all we need.",
"I have health anxiety (hypochondria) and every headache makes me think I'm dying. I've been to the ER six times this year. My family is frustrated, my doctor is running out of patience, and I'm exhausted from being terrified of my own body.",
"I burned out from community work. I was the brother everyone called — masjid events, youth programs, charity drives. I gave everything until there was nothing left. Now I can't even show up for myself. Burnout is real and the ummah enables it.",
"My son has autism and the masjid isn't accommodating. He makes noise during khutbah and people give us dirty looks. One uncle told me to 'control your child.' He's 6 and he's doing his best. We need more compassion in our spaces.",
"I haven't left my house in 11 days. I order food, I work remotely, I pray at home. The outside world feels overwhelming. I know this isn't healthy but right now, my apartment is the only place I feel safe.",
"I experienced religious trauma from an extreme upbringing. Everything was haram, everything was punishment, fear was used to teach religion. I'm slowly reclaiming my faith on my own terms but some days the old fears come back.",
"I told my imam I was suicidal and he said 'remember, suicide is haram.' That's all. No resources, no follow-up, no compassion. Just a ruling. We need our religious leaders to be trained in mental health crisis response.",
"I have misophonia — certain sounds trigger intense rage. I can't eat with my family without wanting to scream. They think I'm being dramatic. This is a real condition and it's isolating when nobody takes it seriously.",
"I forgave my abuser because Islam tells us to forgive. But my body hasn't forgiven. I still flinch, I still have nightmares, I still can't be in a room alone with an older man. Spiritual forgiveness and trauma recovery are two different things.",
"I was the 'gifted kid' who grew into a depressed adult. I had so much potential but my mental health derailed everything. I dropped out of med school, lost my marriage, and now I'm starting over at 31. Life doesn't always go as planned.",
"My wife doesn't believe in mental health. She thinks my depression is laziness. She told me to 'be a man' when I cried. The person I married doesn't have space for my pain and that makes everything worse.",
"I've been journaling every day for a year and it's the best thing I've ever done for my mental health. Getting the thoughts out of my head and onto paper makes them less powerful. Sometimes healing is simpler than we think.",
"I have CPTSD from growing up in a war zone. We came to the West as refugees and everyone thinks we should be 'grateful.' I am grateful. I'm also traumatized. Both things can be true at the same time.",
"I smile during the day and scream into my pillow at night. The gap between who I am publicly and who I am privately is getting wider. I'm afraid that one day the real me will bleed through and everyone will leave.",
"My panic attacks come without warning. In meetings, at the grocery store, picking up my kids from school. My heart races, I can't breathe, the world tilts. And then it passes and I pretend nothing happened. Every single time.",
"I went to a Muslim therapist and she quoted hadith the entire session. I didn't need hadith — I needed someone to help me process my trauma. Not all Muslim therapists are good just because they're Muslim. Find someone qualified.",
"I'm agoraphobic and I can't go to Jummah. The guilt of missing prayers at the masjid compounds the anxiety. I pray at home and ask Allah to accept it. Mental illness shouldn't make me feel like a bad Muslim but it does.",
"I was misdiagnosed for 5 years. They said depression, it was actually PTSD. The right diagnosis changed everything — the right medication, the right therapy, actual progress. If something isn't working, push for answers.",
"I cope with stress by sleeping. Not drugs, not alcohol — sleep. I sleep 14 hours on bad days. People don't recognize it as a problem because 'at least it's not destructive.' But I'm sleeping my life away and calling it rest.",
"My brother took his own life last Ramadan. The community whispered instead of supporting us. Some people said he's in hellfire. How dare they make that judgment. Only Allah knows his pain. Only Allah knows his fate.",
"I have rejection sensitivity and it makes every social interaction excruciating. A friend doesn't text back and I'm convinced they hate me. It's exhausting being this sensitive in a world that rewards thick skin.",
"I started medication for anxiety and my mom cried. She said I was 'putting chemicals in my body instead of trusting Allah.' Mom, Allah sent those chemicals through the hands of a doctor. That IS tawakkul.",
"The best thing I ever did was tell someone I wasn't okay. Just saying the words out loud — 'I'm not okay' — to another person broke something open in me. You don't have to carry it alone. Tell someone. Anyone. Today.",
"I've been going through the motions of life for so long that I forgot what it feels like to actually be present. I eat but don't taste. I pray but don't feel. I exist but I don't live. When does the numbness end?",
"I was gaslit by my parents for years and I'm only now realizing it was abuse. 'We did everything for you, you should be grateful.' Providing for your child doesn't give you the right to destroy their self-worth.",
"My grief from losing my father turned into clinical depression. The community gave me 3 days of condolences and then expected me to move on. Grief doesn't follow a timeline. I'm still crying a year later and that's okay.",
"I have body dysmorphia and I can't look in the mirror without seeing flaws that probably don't exist. Getting dressed takes me an hour because nothing looks right. Social media made it worse. Comparison is truly the thief of joy.",
"I'm a revert and the isolation triggered my depression. I lost my old friends, my family doesn't understand me, and the Muslim community is welcoming on the surface but I still eat iftar alone most nights.",
"My child is struggling with anxiety and the school says she's 'fine.' She's not fine — she cries every morning before school, she's pulling her hair out, she can't sleep. I feel helpless watching my baby suffer.",
"I finally told my best friend about my depression and she said 'but you have so much to be grateful for.' I know I do. Depression doesn't care about your blessings. It takes them and makes them invisible.",
"Therapy taught me that my parents' approval is not the same as my self-worth. I spent 28 years confusing the two. If you grew up in a household where love was conditional on performance, please hear me: you are enough as you are.",
"I have dermatillomania — I pick at my skin compulsively when I'm anxious. My arms are scarred. I wear long sleeves even in summer. People think I'm conservative but really I'm just hiding.",
"I used to pray for death. Not suicide — just for Allah to take me in my sleep so it wouldn't be haram. That's how bad it got. I'm better now, alhamdulillah, but I'll never forget the darkness of wanting to not exist.",
"I'm a crisis counselor at a Muslim helpline and the stories I hear every night would break you. The ummah is hurting in ways we don't talk about. We need more resources, more funding, more trained volunteers. This is a crisis.",
"My ADHD went undiagnosed until I was 30 because 'girls don't get ADHD.' I spent my whole life thinking I was lazy, scattered, broken. A diagnosis at 30 changed everything. Late diagnosis is still diagnosis. It's still valid.",
"I can't afford therapy. I know I need it but it's $150 a session and my insurance doesn't cover it. So I suffer in silence because mental healthcare in this country is a privilege, not a right. When will this change?",
"I wake up every day and choose to keep going. That's my jihad — the struggle against my own mind. Some days I win. Some days I barely survive. But I'm still here and that counts for something.",
"I started volunteering at an animal shelter and it's helped my depression more than anything. Taking care of something that needs you gives you a reason to show up. Sometimes healing comes from unexpected places.",
"My father has narcissistic personality disorder and I didn't realize it until therapy. Every family dynamic I thought was normal was actually abusive. Unlearning 25 years of manipulation is the hardest work I've ever done.",
"I'm a university student and the academic pressure is destroying me. I need to get straight A's to keep my scholarship, I work part-time, I help at home. I sleep 4 hours. This isn't living — this is surviving.",
"After my miscarriage, I developed severe anxiety about pregnancy. I want another child but the fear is paralyzing. My body remembers the loss even when my mind tries to move on. Grief lives in the body.",
"The most Islamic thing you can do for someone struggling with mental health is to sit with them in their pain without trying to fix it. Don't quote ayahs. Don't say 'Allah tests those He loves.' Just be present. That's enough.",
"I'm addicted to my phone and I know it's making my anxiety worse. I pick it up 200 times a day. The dopamine hits from notifications are the only thing that makes me feel something. Digital addiction is real and nobody talks about it.",
"I went to hajj hoping it would cure my depression. It didn't. I felt guilty for being depressed in the holiest place on earth. But you know what? I came back with the understanding that healing is a process, not a destination.",
"My teacher noticed I was struggling before I did. She pulled me aside and said 'you don't have to be okay all the time.' I broke down in her office. Sometimes the right words from the right person at the right time save a life.",
"I have seasonal depression and every winter I disappear. My friends think I'm flaky. My family thinks I'm lazy. My brain is literally running on less serotonin because the sun went away. This is biochemistry, not character.",
"I stopped comparing my healing to others' and everything changed. Your journey is yours. Someone else's recovery timeline has nothing to do with your own. Go at your pace. It's not a race.",
"I've been sober for 3 years, alhamdulillah. To anyone struggling with addiction — you are not your worst moment. You are not beyond redemption. The door of tawbah is always open and so is the door of recovery.",
"I lay in bed for 6 hours today unable to move. Not physically — mentally. My body was capable but my mind had shut down. I missed work, missed prayers, missed life. And tomorrow I'll wake up and try again.",
"I wish someone had told me earlier that asking for help is strength, not weakness. I spent 5 years suffering alone because I thought vulnerability was failure. The bravest thing I've ever done was say 'I need help.'",
"My grandmother's generation didn't have the language for mental health. She had 'nerves.' My mother had 'stress.' I have 'generalized anxiety disorder.' Same pain, three generations, different words. But at least now we can name it.",
"If you take nothing else from this post, take this: you are not a burden. Your pain is not a burden. The people who love you want to help carry it. Let them. That's what community means.",
"I replaced doom-scrolling with dhikr before bed and my sleep quality improved dramatically. SubhanAllah 33, Alhamdulillah 33, Allahu Akbar 34. It doesn't fix everything but it quiets the noise. Small changes matter.",
"I was afraid to start medication because I thought it meant I was weak. 6 months on the right prescription and I can feel joy again. I can taste food again. I can pray with presence. Medication gave me back my life.",
"Mental health tip from someone who's been in the trenches: routines save lives. Wake up at the same time. Eat at the same time. Pray at the same time. When your mind is chaos, structure becomes a lifeline.",
"I'm writing this at 3am because I can't sleep. Again. Insomnia has been my unwanted companion for months. My body is exhausted but my mind won't stop. If you're also awake right now — salaam. You're not alone in the dark.",
"I finally understand that sabr doesn't mean suffering in silence. Sabr means persevering through difficulty while actively seeking help, making dua, AND taking action. Sitting in pain and calling it patience is not what Islam teaches.",
"My inner child needed to hear these words so I'll say them for anyone who needs them too: you were just a kid. It wasn't your fault. You didn't deserve what happened to you. And you deserved better than what you got.",
"Healing isn't beautiful. Nobody tells you that. It's ugly crying in your car, it's cancelled plans, it's therapy homework that makes you feel worse before better. But on the other side of that ugliness is freedom. Keep going.",
];

const family=[
"My parents sacrificed everything to bring us to this country and now they're disappointed I'm not a doctor. I'm a teacher. I make a difference every day but in their eyes, I failed because I don't have MD after my name.",
"My father hasn't spoken to me in 2 years because I married outside our culture. He was at the masjid today giving a khutbah about the importance of family. The hypocrisy burns.",
"I'm the eldest daughter and I've been parentified since I was 10. I raised my siblings, I translated for my parents, I handled bills at 14. Now everyone's grown up and nobody acknowledges what I sacrificed. I lost my childhood.",
"My mother compares me to my cousin at every family gathering. 'Look at Fatima, she's a doctor and married.' Cool. I'm me. I have my own timeline. Can that be enough?",
"My parents are getting old and I'm the only child in the country. All my siblings are overseas. The full weight of their care is on me. I love them but I'm 28 and I have no life outside of being their caregiver.",
"I came out to my family as struggling with same-sex attraction. I'm not acting on it. I'm choosing my faith. But my father looks at me differently now. Like I'm broken. His eyes used to be warm. Now they're just... disappointed.",
"My older brother is the golden child who can do no wrong. I graduated top of my class — 'that's nice.' He passed his exam on the third try — family celebration. The favoritism is so obvious it's almost funny. Almost.",
"My parents got divorced and both are using me as a messenger. 'Tell your father...' 'Tell your mother...' I'm not your translator. I'm your child. And I'm falling apart trying to hold everyone together.",
"I found out I was adopted at 25. My parents — or the people I thought were my parents — never told me. My whole identity feels like a lie. I love them but I don't know who I am anymore.",
"My mother-in-law told me my cooking will never be as good as hers. Then she told my husband the same thing. At the same dinner. While eating the food I spent 3 hours making. I didn't say anything. I just smiled and died inside.",
"My teenage daughter told me she doesn't believe in God. I didn't yell, I didn't lecture. I just asked her why. She talked for an hour about her doubts. I think she just needed someone to listen without judgment. Parenting is terrifying.",
"My father was physically abusive when I was growing up. He's old now and needs my help. Everyone says 'honor your parents' but they don't know what he did behind closed doors. How do I honor someone who broke me?",
"I immigrated to support my family back home. I send $1,500 every month. I live in a studio apartment, I eat rice and beans, I work two jobs. When I visit, they think I'm rich because I live in America. They have no idea.",
"My parents won't let me move out until I'm married. I'm 27. I pay rent, I cook, I clean, I follow their rules. But I also have a master's degree and a career. At what point do I get to live my own life?",
"My family gossips about everyone. Weddings, funerals, iftars — nothing is safe. They'll smile in someone's face and destroy their reputation over tea. I've started distancing myself and now I'm the 'difficult one.'",
"I raised my younger siblings because both my parents worked. I changed diapers at 12, made lunches at 13, did school runs at 16. Now everyone's grown and no one thanks me. They don't even remember. But my body remembers every sacrifice.",
"My parents fight every night. They think we can't hear them but the walls are thin. I'm 16 and I put my headphones on and pretend I'm somewhere else. I love them both but I hate what they become together.",
"My father told my brother 'you're the man of the house' when he was 8. He took it literally. Now at 19, he tries to control me, my mother, and my younger sisters. He polices our clothes, our friends, our phones. We created a monster.",
"I can't afford to visit my mother in my home country. She's sick and I'm working three minimum wage jobs just to survive. The guilt of being away from her while she needs me is a weight I carry every single second.",
"My family disowned my sister for marrying a non-Muslim. She's happy, she's loved, she's thriving. But she doesn't exist to us anymore. I secretly call her every week. Losing a sibling over love feels like a death nobody mourns.",
"My parents have never said 'I love you' to me. Not once in 30 years. I know they do — they show it through food, sacrifice, worry. But sometimes I just need the words. Am I wrong for wanting to hear it?",
"I'm the family therapist, the family bank, the family mediator, and the family tech support. But when I need something? 'You're so strong, you'll figure it out.' Being the strong one means nobody ever asks if you're okay.",
"My mother-in-law moves things in my house when she visits. She reorganizes my kitchen cabinets, rearranges my spice rack, changes the position of furniture. It's passive-aggressive territorial behavior and my husband thinks I'm overreacting.",
"My parents play favorites with their grandchildren. My brother's kids get expensive gifts, trips, attention. My kids get whatever's left over. They notice. My 7-year-old asked me why grandma loves her cousins more. I had no answer.",
"I chose to be a stay-at-home dad while my wife works. My family is mortified. My father told me I've 'lost my manhood.' My wife makes triple what I could earn. I'm raising our kids with love and presence. That's not weakness.",
"My sibling has a drug problem and my parents are in denial. They cover for him, give him money, make excuses. I've tried to help but at this point, their enabling is as dangerous as his addiction. I can't save someone who isn't ready.",
"I'm the first in my family to go to college and the pressure is unbearable. I'm not just studying for me — I'm studying for every sacrifice my parents made, every midnight shift, every skipped meal. The weight of their dreams is on my shoulders.",
"My family makes fun of my weight at every gathering. 'You've gotten so big!' is their greeting. Not 'how are you?' Not 'we missed you.' Just commentary on my body. They call it 'honesty.' I call it cruelty.",
"My parents refuse to make a will because 'it's morbid.' They have significant assets and six children with very different financial situations. This is going to tear our family apart when they're gone and nobody wants to address it.",
"I'm a middle child and I've been invisible my whole life. My older brother got the expectations, my younger sister got the attention. I got 'you're so easy, we never have to worry about you.' Being easy to overlook isn't a compliment.",
"My grandmother raised me while my parents worked. She died last month and I feel like I lost my real parent. I loved my parents but she was my home. The grief is overwhelming because nobody else seems to miss her like I do.",
"My family pressures me to give sadaqah to relatives back home but some of those relatives have more money than we do. They just hide it. I've sent thousands of dollars to people who drive better cars than mine. When does obligation become exploitation?",
"I'm taking care of my mother who has Alzheimer's. Yesterday she looked at me and asked 'who are you?' Her own daughter. I fed her, bathed her, and put her to bed while swallowing tears. Some days I grieve her while she's still alive.",
"My father worked 16-hour days my entire childhood. I barely knew him. Now he's retired and wants a relationship. Part of me wants that too. Part of me is angry at all the years he chose work over us. Forgiveness is a process.",
"My toxic family members use Islam as a weapon. 'Obey your parents unconditionally.' 'Cutting ties is haram.' They twist beautiful teachings into chains. Healthy boundaries aren't haram. Protecting your peace isn't sinful.",
"I moved to a new city for work and the loneliness of being away from family is crushing. I Facetime them every night but it's not the same. I miss my mother's cooking, my father's jokes, my sister's annoying laugh. Homesickness hits different at 2am.",
"My parents treat my brother's wife like a queen and treat my husband like an outsider. The double standard is exhausting. When I bring it up, my mom says 'it's different for boys.' No, mom, it's just unfair.",
"I grew up in a household where anger was the only acceptable emotion. Happy? Don't show off. Sad? Stop being dramatic. Hurt? Toughen up. Angry? Now that was allowed. It took therapy to learn that I'm allowed to feel everything.",
"My family still talks about my divorce like it happened last week. It was 5 years ago. I've moved on, remarried, and I'm happy. But every Eid, someone brings it up. Our community treats divorce like a permanent stain that never fades.",
"I'm 24 and I still sleep in the same room as my two siblings because our apartment is too small. Privacy is a luxury when you're an immigrant family of 6 in a two-bedroom. I just want a door I can close.",
"My mother-in-law called CPS on us because we told her she couldn't live with us. She made false allegations. The investigation found nothing but the trust is permanently destroyed. She weaponized the system against her own grandchildren.",
"My parents never apologize. For anything. I've never heard 'I'm sorry' from either of them. They just act normal after hurting you and expect you to move on. No accountability, ever. It teaches you that your feelings don't matter.",
"I have a family group chat with 47 people and it's the most toxic place on the internet. Gossip, passive-aggressive voice notes, unsolicited opinions about everyone's life choices. I muted it and I've never been more at peace.",
"My father is an imam and he's completely different at home. At the masjid he's gentle, patient, beloved. At home he's harsh, critical, and demanding. I struggle to respect the Islam he preaches because I see who he is behind closed doors.",
"I took a DNA test and discovered I have a half-sibling my father never told us about. He has an entire other child from a relationship before my mother. The secrets families keep can break you if you let them.",
"My parents chose my older sister's education over mine because they could only afford one. She became a doctor. I work retail. I don't resent her — I resent the system that forced my parents to choose which daughter got a future.",
"I'm 30 and my mother still guilt-trips me for not calling her every day. If I call every other day, I get 'I could have died and you wouldn't know.' The emotional manipulation is suffocating but she's my mom and I love her.",
"My brother came out as gay and my parents kicked him out. He was 17. Seventeen. He lived in his car for two months before a friend's family took him in. What kind of parents abandon their child? He needed love, not exile.",
"I just realized that the 'funny stories' my parents tell about my childhood are actually descriptions of neglect. 'Remember when you made dinner for yourself at 6 because we forgot?' That's not funny, that's failure.",
"My family uses money as control. They pay for things and then hold it over your head forever. 'We paid for your wedding.' 'We helped with your car.' Every favor comes with strings and an expiration date that never arrives.",
"I visit my parents out of obligation, not desire. That sentence makes me feel like the worst Muslim alive. But every visit leaves me emotionally drained for a week. Is dutiful misery really what Islam asks of children?",
"My mother has been diagnosed with cancer and I'm trying to be strong for her. But when I close my bathroom door, I fall apart. She's my best friend, my first call, my safe place. I can't imagine a world without her in it.",
"I have a beautiful family — loving spouse, three healthy kids, a house, stability. Alhamdulillah for everything. But sometimes I look at my life and feel a hollowness I can't explain. Gratitude and emptiness can coexist and that confuses me.",
"My teenage son asked me why we're Muslim. Instead of getting defensive, I sat with him and we talked for hours. His questions were thoughtful, not rebellious. Sometimes our kids don't need answers — they need to know it's safe to ask.",
"I caught my father lying to my mother about his finances. He's been hiding money for years. Tens of thousands. I don't know whether to tell her or keep his secret. Both options make me feel sick.",
"My parents want me to name my baby after a relative I don't like. They say it's tradition. I say my child, my choice. What seemed like a small disagreement has turned into a family-wide battle and the baby isn't even born yet.",
"My family still treats me like I'm 12. I'm a 35-year-old woman with a career, a home, and a fully functioning life. But at family gatherings, my opinions are dismissed because 'you're still young.' When does 'young' end in an immigrant family?",
"My siblings and I don't talk to each other. Not because of a fight — we just... drifted. We share parents and a last name and nothing else. Sometimes I see posts about siblings being best friends and I feel the absence deeply.",
"I forgave my mother for everything — the criticism, the comparison, the conditional love. Not for her sake, but for mine. I was carrying 30 years of resentment and it was heavier than anything she ever did to me. Letting go saved me.",
"My parents retired and now they call me 7 times a day. Every time I don't pick up, it's a guilt trip. I love them but I'm in meetings, I'm parenting, I'm living. The transition from independent adult to on-call child support is hard.",
"I grew up translating doctor appointments, legal documents, and parent-teacher conferences for my parents. I was 9. They called it 'helping.' I now know it was too much responsibility for a child. But I'd do it again because that's love.",
"My step-mother tries really hard and I don't give her enough credit. She married my dad knowing he had 4 kids and she chose to love us anyway. She's not my birth mother but she mothers me every single day. Some bonds aren't blood.",
"My cousin's wedding cost $150,000. My uncle took loans for it. Now the couple is getting divorced after 18 months. The wedding was for the family's ego, not for the couple's happiness. When will our community learn?",
"I'm the only practicing Muslim in my family. They celebrate all the cultural holidays but skip Eid. They eat haram and question why I don't. Being the 'religious one' in a secular family is isolating. I feel like a stranger in my own home.",
"My parents didn't attend my graduation. They said they were busy but they went to my cousin's a month later. It was the proudest day of my life and the chairs I saved for them were empty. Some wounds from parents never fully close.",
"My older sister protected me from my father's anger my entire childhood. She took the hits so I wouldn't have to. She never told me until last year. I owe her everything and I can never repay it. Some heroes don't wear capes — they're your big sister.",
"I became a parent and suddenly understood my own parents. The sleepless nights, the sacrifice, the constant worry. I called my mom and said 'thank you' and she cried. Sometimes understanding comes a generation late but it still matters.",
"My family thinks therapy is airing dirty laundry. 'What happens in this house stays in this house.' But what happened in this house broke me. I chose healing over loyalty to silence and I'm not sorry.",
"I have 4 siblings and we've started a family group therapy session. Once a month, we all get on video with a therapist and talk about our childhood. It's painful but we're finally being honest with each other. Healing can be a family project.",
"My dad calls me his 'little man' and I'm 32. He still ruffles my hair. He still gives me money even though I make more than him. He still checks my tires when I visit. I don't need any of it but I need all of it. Appreciate your fathers while you have them.",
"I set boundaries with my toxic aunt and the entire family turned on me. 'She's family, you have to tolerate it.' No. Family is not a free pass for abuse. I'd rather be the 'disrespectful' niece than the broken one.",
"My parents fled a war with nothing and built a life in a country where they didn't speak the language. Everything I have is because of what they survived. When I complain about anything, I remember — my problems are luxuries compared to theirs.",
"My family finally sat down and had an honest conversation about our childhood. No blame, no defensiveness. Just truth. It took 20 years but we finally said the unsaid things. The room was heavy but when we left, we were lighter. Communication heals.",
"I lost custody of my kids and it's the darkest chapter of my life. I was the primary parent for 6 years and a judge decided otherwise in 20 minutes. I see them every other weekend and I count the hours in between. This pain has no name.",
"My grandparents don't know how to say 'I love you' but they say it in other ways. My grandfather saves newspaper clippings he thinks I'd like. My grandmother cooks my favorite meal every time I visit, even though it takes her all day. Love has a thousand languages.",
"I stopped attending family gatherings where my uncle drinks alcohol. My family says I'm being extreme. I say I'm protecting my boundaries and my children. Standing firm in your values makes you unpopular but it keeps you whole.",
"I am raising my children differently than how I was raised. Less fear, more love. Less control, more trust. Less shame, more guidance. Breaking generational cycles is lonely work because your own parents often don't understand why you're doing it differently.",
];

const faith=[
"I haven't prayed in 6 months. Not because I don't believe — I do. I just feel so far from Allah that the prayer feels hollow. Like I'm going through motions with a heart that's empty. Does He even want to hear from someone like me?",
"I memorized the Quran by age 12 and burned out by 15. The pressure, the competition, the praise — none of it was about Allah. It was about performance. I'm 23 now and trying to rebuild a genuine relationship with the Quran. Starting from Al-Fatiha.",
"Someone asked me why I wear hijab and for the first time, I didn't have a good answer. I've worn it since I was 9 because my parents told me to. I've never questioned it until now. Is obedience the same as conviction?",
"I stood at Arafat during Hajj and felt absolutely nothing. Everyone around me was crying, their hands raised to the sky. I was standing in the most sacred place on earth and I felt empty. The guilt of that emptiness haunts me still.",
"I'm questioning everything I was taught about Islam. Not the core beliefs — those I hold firmly. But the cultural practices that were presented as religion. The more I study on my own, the more I realize how much culture was dressed up as deen.",
"I reverted to Islam 3 years ago and sometimes I feel like a tourist in my own religion. Born Muslims have community, culture, family traditions. I have a shahada and a lot of catching up to do. It's lonely being a convert.",
"I found a community of Muslims who welcomed me with open arms. No gatekeeping, no judgment, no cultural barriers. Just love for Allah and His messenger. They taught me that Islam isn't about perfection — it's about direction. That changed everything.",
"I argue with Allah sometimes. Not out of disrespect — out of pain. I know He hears me. I know He tests those He loves. But some days the test feels like punishment and I don't know the difference anymore.",
"My iman hit rock bottom after my mother's death. She was the most pious woman I knew — tahajjud every night, charity every week, never missed a prayer. She died of cancer at 52. I'm angry at a decree I'm not supposed to question.",
"I converted from Christianity to Islam and losing my family's religion felt like losing my family. My mom cried for weeks. My dad still won't speak to me. I chose truth but truth is expensive and I'm still paying the price.",
"The most powerful ayah for me right now: 'Indeed, with hardship comes ease.' I've been repeating it for months. Some days I believe it. Some days it's just words. But I keep saying it because I have nothing else to hold onto.",
"I went to an Islamic lecture and the scholar said something that changed my life: 'Allah doesn't need your prayer. YOU need your prayer.' Salah isn't a favor we do for God — it's a gift He gave us. That reframe changed everything.",
"I struggle with prayer not because I'm lazy but because I have ADHD and standing still for 10 minutes while controlling my thoughts is incredibly difficult. Please stop judging people who struggle with salah. You don't know their battles.",
"I read a translation of the Quran in English for the first time and cried for three hours. I've been reciting Arabic my whole life without understanding. When I finally read the meaning — SubhanAllah. The Quran is a conversation and I'd been missing my side of it.",
"I'm terrified of death. Not because I don't believe in akhirah but because I don't think I've done enough. Every sin plays back in my mind like a movie I can't turn off. The fear of standing before Allah keeps me awake at night.",
"I was taught Islam through fear as a child. Hell, punishment, wrath. It took me years to discover the Islam of mercy, love, and hope. The first hadith that healed me: 'My mercy prevails over My wrath.' I wish I'd heard that first.",
"I pray tahajjud not because I'm pious but because I'm desperate. The last third of the night is when I pour out everything to Allah. The tears in sujood at 4am are the most honest I'll ever be. That's my real salah.",
"I visited Madinah and when I saw the green dome, I collapsed. The love I felt for the Prophet (SAW) in that moment was physical. I didn't expect it. I've studied seerah for years but nothing prepares you for actually being there.",
"A non-Muslim colleague asked me to explain Islam in one sentence. I said: 'Surrender your ego to the Creator and serve His creation with kindness.' He paused and said 'That's beautiful.' It is. Sometimes we forget how beautiful our deen actually is.",
"I fast Mondays and Thursdays and it's completely transformed my relationship with food, gratitude, and patience. The Sunnah fasts are underrated. Something about voluntary hunger reminds you that this dunya is temporary.",
"I used to think tawakkul meant sitting back and waiting for Allah to fix everything. Now I understand it means doing everything in your power and then trusting Allah with the result. Trust is active, not passive. That distinction changed my life.",
"My favorite moment in Ramadan isn't iftar — it's the last 10 minutes before Maghrib. When your stomach is empty, your eyes are tired, and your dua feels the most raw and honest. That's when I feel closest to Allah.",
"I asked my shaykh why bad things happen to good people. He said, 'Would you rather be tested in this life, which is temporary, or in the next, which is eternal?' That perspective shift hit me like a truck.",
"I keep a dua journal. Every time I make dua for something specific, I write it down with the date. Months later, I go back and see how many were answered. The record of Allah's responses is the most convincing proof of His existence I have.",
"I left Islam for 2 years. I tried atheism, agnosticism, even explored other religions. Nothing felt true. When I came back to salah — that first sujood after 2 years — I understood what 'coming home' means. Allah waited for me.",
"A Christian friend asked me why Muslims pray five times a day. I said, 'How many times a day do you check your phone? Prayer is my check-in with the One who actually matters.' She started visiting the masjid last month.",
"I finally understand why the Prophet (SAW) said patience is light. Not fire, not strength — light. Because patience doesn't burn through pain, it illuminates it. You start to see the wisdom in the test. SubhanAllah.",
"I'm studying Arabic so I can understand the Quran without translation. It's hard — I'm 35 and learning a new language. But every word I understand in salah makes the prayer deeper. The effort is worth every struggle.",
"I made tawbah for the same sin for the hundredth time. And you know what? I'll make it for the hundred and first. Because Allah's mercy doesn't have a limit, so my repentance shouldn't either. Keep coming back. He's always there.",
"My non-Muslim neighbor brought us food during Ramadan because 'you guys must be tired from fasting all day.' That simple act of kindness did more for interfaith dialogue than any conference I've attended. Kindness is a universal language.",
"I've been doing dhikr consistently for 30 days — SubhanAllah, Alhamdulillah, Allahu Akbar after every prayer. My anxiety has measurably decreased. I'm not saying it's a cure but there's something to repeating words of peace when your mind is at war.",
"I'm a scientist and a Muslim. People act like that's a contradiction. It's not. The more I study the universe, the more convinced I become that none of this is random. Science shows me the 'how.' Islam shows me the 'why.'",
"I lost my wallet with $500 in it. Instead of panicking, I said 'Inna lillahi wa inna ilayhi raji'un' and moved on. Someone found it and returned it — all cash included. I don't know if that's barakah or coincidence but I know which one I believe.",
"My imam gave a khutbah about perfectionism in worship and it freed me. He said, 'Allah doesn't want your perfection. He wants your presence. Show up broken, show up tired, show up confused — just show up.' I've prayed every salah since.",
"I read Surah Ad-Duha when I'm sad. 'Your Lord has not abandoned you, nor has He become hateful.' Every time I read it, I cry. The Quran speaks to exactly what you need when you need it. It's alive in a way no other book is.",
"I asked Allah for patience and He gave me situations that required it. I asked for strength and He gave me challenges that built it. I asked for love and He gave me people who needed mine. Allah answers duas in the form of growth, not gifts.",
"I stopped following Instagram imams who only post about haram and hellfire. I started following ones who teach about mercy, hope, and the beauty of the Sunnah. My relationship with Islam transformed. The lens you see your religion through matters.",
"I was at the lowest point of my life when an old man at the masjid grabbed my hand and said 'Whatever it is, it's temporary. But Allah's love for you? That's permanent.' I don't know his name but his words saved my life that night.",
"I pray Istikhara every night for direction in my life. Not just for marriage or career — for everything. 'O Allah, if this is good for me, make it easy. If it isn't, remove it.' That dua has simplified every difficult decision I've ever made.",
"Ramadan taught me that I'm capable of more than I think. If I can go 16 hours without food and water, I can resist any temptation. Fasting isn't deprivation — it's a yearly proof that your nafs doesn't control you. You control it.",
"I have a 5-year-old and she asked me where Allah is. I said 'everywhere.' She looked around the room, smiled, and said 'even here? Cool.' Children understand tawhid better than scholars. Their faith is pure and uncomplicated.",
"The Prophet (SAW) was described as a walking Quran. That means Islam isn't just a book you read — it's a life you live. Character is worship. Kindness is worship. Patience is worship. Everything becomes ibadah when your intention is right.",
"I finally memorized Surah Al-Mulk and I recite it before sleep every night. Knowing that these words protect you in the grave gives me a peace I can't describe. Start with one surah. Just one. And let it grow from there.",
"I think the most underrated act of worship is husn al-dhann — having a good opinion of Allah. Believing that whatever He decrees is for your ultimate good, even when it doesn't feel like it. That belief alone is a form of worship.",
"I was angry at Allah for years. My therapist (who's Muslim) told me: 'It's okay to be angry at Allah. He can handle your anger. What He can't handle is your silence. Keep talking to Him, even if you're yelling.' That permission to be honest in dua changed everything.",
"I found a prayer spot in my office and I pray Dhuhr there every day. One day a coworker asked what I was doing. I explained. She said 'I wish I had something that consistent in my life.' Islam gives us structure in a chaotic world.",
"Every time I think about giving up on Islam, I read the stories of the Sahabah. These were people who were tortured, exiled, starved — and they never wavered. My problems are nothing compared to theirs. If they held on, I can hold on.",
"I prayed for something for 7 years and last month it happened. SEVEN YEARS of asking. If I had stopped at year 6, I would have missed it. Never stop making dua. Allah's timeline is not yours and His is always better.",
"The five daily prayers have given me something no self-help book ever could: rhythm. My day has structure. No matter how chaotic life gets, five times a day I stop, face Makkah, and remember who I am and Who I belong to.",
"I read that the Prophet (SAW) mended his own shoes and sewed his own clothes. The greatest man to ever live did household chores. The next time someone says housework is 'beneath' them, remember whose sunnah it actually is.",
"I went to Umrah solo and it was the most healing experience of my life. No distractions, no social obligations. Just me and Allah. I did tawaf alone at 3am and every step felt like a prayer. If you ever get the chance — go alone at least once.",
"I asked my 80-year-old grandfather what the most important thing in Islam is. He didn't say prayer or fasting. He said 'husn al-khuluq — good character. You can pray all night but if you harm people by day, what is the point?' Wisdom from a lifetime of faith.",
"I teach Sunday school and one of my students asked 'If Allah already knows what we'll choose, why does He test us?' I said, 'The test isn't for Him to learn about you. It's for you to learn about yourself.' His eyes got wide. Kids ask the best questions.",
"I memorized the 99 Names of Allah and the one that hits hardest is Al-Wadud — The Most Loving. Not just loving. THE MOST loving. More than any parent, any spouse, any creation. The Creator of love IS love. That's enough to keep going.",
"My favorite act of worship is giving charity anonymously. Not for social media, not for tax receipts. Just putting money where someone needs it and walking away. Knowing only Allah saw it makes it taste different. Purity of intention changes everything.",
"I converted at 19 and I'm now 34. Islam has been the most consistent, stable, reliable thing in my life when everything else fell apart. Jobs came and went, relationships ended, people changed. But my salah was always there. Always five. Always sure.",
"I used to think I was too sinful for Allah to love me. Then I learned about Hadith Qudsi: 'If you come to Me walking, I come to you running.' He doesn't wait for us to be perfect. He meets us exactly where we are. That's not just mercy — that's love.",
"I have doubts sometimes. Real, shaking doubts. But I've learned that doubt doesn't destroy faith — it refines it. Every question I've wrestled with has led me to a deeper understanding. Faith without doubt is untested. And untested faith is fragile.",
"The adhan still gives me chills. After 30+ years of hearing it, the words 'Allahu Akbar' still hit my chest differently. Some things don't age. Some truths don't fade. The call to prayer is one of them.",
"I pray for people I don't like. That's the level of Islam I'm trying to reach. Not just praying for my friends and family — but for the uncle who insulted me, the colleague who wronged me, the stranger who cut me off in traffic. Dua for your enemies is the hardest sunnah.",
"I asked my wife to pray with me and we started praying Fajr together. That 5 minutes before dawn, standing side by side, is the most intimate part of our marriage. We don't just share a life — we share a qiblah. Find someone who'll face Makkah with you.",
"Someone told me 'Islam is rigid' and I laughed. A religion that allows you to pray on a plane, break your fast for travel, pay zakat on your own terms, and make tawbah unlimited times is anything but rigid. Islam is the most flexible system I've ever encountered.",
"I keep a gratitude journal as an act of worship. Every night I write 3 things I'm grateful for and say Alhamdulillah. On bad days, it's just 'I'm alive, I have food, I have shelter.' But even that reminds me — I'm richer than I think.",
"The Quran says 'Remember Me and I will remember you.' That's not a transaction — it's a relationship. The Creator of 200 billion galaxies promises to remember ME if I remember HIM. How is that not the greatest deal ever offered?",
"I'm not a perfect Muslim. I miss prayers sometimes. I backbite occasionally. I lose my temper. But every day I try to be slightly better than yesterday. That's my Islam — not perfection but persistent, imperfect, honest effort. And I believe that's enough.",
];

async function insertBatch(posts,tag){
  var batchSize=25;
  for(var i=0;i<posts.length;i+=batchSize){
    var batch=posts.slice(i,i+batchSize).map(function(content){
      return {
        anon_name:randName(),
        content:content,
        tag:tag,
        likes:randLikes(),
        has_fund:false,
        fund_goal:0,
        fund_raised:0,
        created_at:randDate()
      };
    });
    var res=await fetch(SURL+'posts',{
      method:'POST',
      headers:{
        'apikey':SKEY,
        'Authorization':'Bearer '+SKEY,
        'Content-Type':'application/json',
        'Prefer':'return=minimal'
      },
      body:JSON.stringify(batch)
    });
    if(!res.ok){
      console.error('Failed batch at index',i,'for tag',tag,res.status,await res.text());
    } else {
      console.log('Inserted',Math.min(i+batchSize,posts.length),'/',posts.length,tag);
    }
  }
}

async function main(){
  console.log('Seeding 400 posts...\n');
  console.log('--- Marriage (100 posts) ---');
  await insertBatch(marriage,'m');
  console.log('\n--- Mental Health (100 posts) ---');
  await insertBatch(mentalHealth,'me');
  console.log('\n--- Family (100 posts) ---');
  await insertBatch(family,'fa');
  console.log('\n--- Faith (100 posts) ---');
  await insertBatch(faith,'fai');
  console.log('\nDone! 400 posts seeded.');
}

main();
